adding windows registry functionality
vadim-ruzh/Logger pull request #16
Opened 2022-04-11 10:37 UTC by vadim-ruzh

-added an additional level of logging, depending on the parameter in the registry

2022-04-12 04:15 UTC, reficul0 requested changes
Нужны доработки. 

Очень не хвататет комментариев к функциям, которые бы поясняли подводные камни(тег \remark), вида что происходит если вылетает исключение. Можно ли вызывать функцию дважды(для закрытия/открытия актуально).

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
> +	bool dbgMode;
m_isDbgMode

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +#include <codecvt>
все инклуды должны быть в самом начале файла

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +inline std::wstring utf8toUtf16(const std::string& str)
Эта функциональность уже есть в `boost::locale::conv::utf_to_utf<wchar_t>(str)` для utf8->utf16 и `boost::locale::conv::utf_to_utf<char>(wstr)` для utf16->utf8

2022-04-12 04:15 UTC, reficul0 commented on Logger/Trace.h
> +	debug,
Значения перечисления, по кодстайлу которого мы придерживаемся, начинаются с заглавной буквы

2022-04-12 04:15 UTC, reficul0 commented on Logger/Trace.h
> +	else\
думаю, что можно обойтись одним if-ом без else, если правильно составить условие

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
>  	Logger(const std::string& programName = "") :
```c++
Logger(const std::string& programName = "")
   : dbgMode(CheckDbg(programName.empty() ? GetExecutableName() : programName))
   , m_pathToLog(InitPathToLog(programName.empty() ? GetExecutableName() : programName))
{
}
```

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
>  	Logger(const std::string& programName = "") :
DRY: `programName.empty() ? GetExecutableName() : programName`

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
> +		//registry path
Комментарий не должен констатировать то, что делает код. Есть смысл добавлять комментарий только если он описывает то, что не могут описать названия переменных и методов, к примеру обобщает очень сложный алгоритм. См. https://refactoring.guru/ru/smells/comments.

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
> +		auto regPath = utf8toUtf16("SOFTWARE\\" + programName);
простые типы с не очень длинным названием ни к чему выводить через auto, лучше сразу писать имя типа, в данном случае std::wstring

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
> +		WinRegManager reg(Hkeys::HkeyCurrentUser, regPath, AccessRights::AccessAll);
Hkeys::HkeyCurrentUser 
DRY: дублирование Hkey в названии значения 

Но не критично, можно и не править.

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
> +		// 0 - ok , !0 - error
код поясняет это намного лучше, чем комментарий. Минус коментария в том, что код поменяется, а комментарий могут забыть поменять. Каждый новый комментарии при рефакторинге, это + к головной боли. Код должен быть максимально самодокументируемым. См. https://habr.com/ru/company/piter/blog/460725/

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
> +	bool CheckDbg(const std::string& programName)
IsDbgModeEnabled

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
> +		if(res < 1000)
Магических чисел в коде нужно избегать. См. https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
> +			return false;
Залоггировать причину?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
> +			return false;
Залоггировать причину?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
> +	bool CheckDbg(const std::string& programName)
Check стоит использовать, если функция будет кидать исключения в случае ошибки при проверке

2022-04-12 04:15 UTC, reficul0 commented on Logger/Logger.cpp
> +	bool dbgMode;
Неиспользуемая переменная?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +	switch (acc)
В таких случаях часто бывает более предпочитаемым подход с картой:
```c++
static std::unordered_map<AccessRights, REGSAM> accessRightsMap 
{
    { AccessRights::AccessWrite, KEY_WRITE },
    { AccessRights::AccessRead, KEY_READ },
    { AccessRights::AccessAll, KEY_ALL_ACCESS }
};
auto accessRightIter = accessRightsMap.find(acc);
return accessRightIter != accessRightsMap.end() 
          ? accessRightIter.second
          : 0;
```

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +enum class Hkeys
Для упрощения реализации обратной совместимости(если такая понадобится), на всякий случай нужно указать базовый тип перечисления. Пусть будет `enum class Hkeys : uint16_t`

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +	HkeyClassesRoot,
```
HkeyClassesRoot = 0,
HkeyCurrentUser,
```

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +inline REGSAM AccessRightsConverter(const AccessRights& acc)
выглидт как то, что ни к чему инлайнить эту функцию

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +inline HKEY HkeysConverter(const Hkeys& key)
см. ревью к AccessRightsConverter

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +inline REGSAM AccessRightsConverter(const AccessRights& acc)
AccessRightsConverter переименовать в ConvertAccessRights. Имя функции должно быть глаголом, а AccessRightsConverter это существительное.

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +	return 0;
А это точно не приведёт к проблемам?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +	return 0;
В REGSAM значение 0 это значение ошибки?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +		OpenKey(key, subKey, access);
Может ли OpenKey выбросить исключение? Если конструктор не отработал до конца(вылетело исключение), то деструктор вызываться не будет. В таком случае произойдёт утечка ресурсов: ключ будет не закрыт.

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +	void OpenKey(const Hkeys& key, const std::wstring& subkey, const AccessRights& access, LSTATUS& err)
нужно описать гарантию исключений, и сказать, надо ли вызвать закрытие ключа если исключение вылетает, или же не надо

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +	void OpenKey(const Hkeys& key, const std::wstring& subkey, const AccessRights& access, LSTATUS& err)
См. https://habr.com/ru/post/126374/

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +		isOpen = true;
не надо защищать внутреннее состояние мьютексом?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +	void OpenKey(const Hkeys& key, const std::wstring& subkey, const AccessRights& access, LSTATUS& err)
Проверка что subkey валидный? (не пуст как минимум)
Зануление ошибки err перед вызовом?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +				mKey = nullptr;
Проверка, что mkey не равен null? Т.е. открытие вызывается до закрытия

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +		isOpen = true;
Проверка, isOpen  закрыт? Т.е. открытие вызывается до закрытия

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +				mKey = nullptr;
Вообще, не до конца понял зачем тут это зануление когда мы ниже устанавливаем значение mKey

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			throw RegException{ status,"Fail open registry key" };
Мы вроде договаривались на коды ошибок, а не исключения. Но не критично, можно не править

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			0,
а вот тут вот хорошо бы написать поясняющие комментарии к тому что это за 0

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			0,
а вот тут вот хорошо бы написать поясняющие комментарии к тому что это за 0

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			nullptr,
а вот тут вот хорошо бы написать поясняющие комментарии к тому что это за nullptr

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			nullptr,
а вот тут вот хорошо бы написать поясняющие комментарии к тому что это за nullptr

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			nullptr);
а вот тут вот хорошо бы написать поясняющие комментарии к тому что это за nullptr

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +	HKEY mKey{ nullptr };
лучше указывать стартовое значение в конструкторе

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +		//noexcept
стоит прописать noexcept в сигнатуре функции:
`DWORD GetDword(const std::wstring& subKey, const std::wstring& valueName, LSTATUS& err) noexcept`

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +	//Reg_DWORD
непонятно назначение комментария

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			nullptr,
что за nullptr?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			err = ERROR_INVALID_HANDLE;
звучит как повод для кастомной ошибки вида ERROR_INVALID_STATE

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			err = ERROR_INVALID_HANDLE;
звучит как повод для кастомной ошибки вида ERROR_INVALID_STATE

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			0,
что за 0?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			reinterpret_cast<LPCBYTE>(&value),
точно безопасно так делать?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +	//except
что за except? если про то что функция бросает исключения, то лучше писать
`DWORD GetDword(const std::wstring& subKey, const std::wstring& valueName) noexcept(false)`

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +	std::wstring GetSz(const std::wstring& subKey, const std::wstring& valueName, LSTATUS& err)
см. ревью к GetDword

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			nullptr,
что за nullptr-ы?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			return nullptr;
выглядит неожиданно, возвращаемое значение wstring, при чём тут указатель?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			nullptr,
что за nullptr?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			&result[0],
`result.c_str()`?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			0,
что за ноль?

2022-04-12 04:15 UTC, reficul0 commented on Logger/Registry.cpp
> +			err = ERROR_INVALID_HANDLE;
звучит как повод для кастомной ошибки вида ERROR_INVALID_STATE

2022-04-30 07:35 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +#include <codecvt>
Исправлено

2022-04-30 07:36 UTC, vadim-ruzh commented on Logger/Trace.h
> +	debug,
Исправлено

2022-04-30 07:38 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			err = ERROR_INVALID_HANDLE;
Добавлен enum class с кодами ошибок

2022-04-30 07:38 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			0,
Добавлены поясняющие комментарии

2022-04-30 07:38 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			&result[0],
Исправлено

2022-04-30 07:38 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			nullptr,
Добавлены поясняющие комментарии

2022-04-30 07:40 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +inline REGSAM AccessRightsConverter(const AccessRights& acc)
Функция убрана

2022-04-30 07:41 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +	HkeyClassesRoot,
enum была убран,заменен на map

2022-04-30 07:41 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +enum class Hkeys
enum была убран,заменен на map

2022-04-30 07:41 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +	switch (acc)
Заменено на другое решение

2022-04-30 07:42 UTC, vadim-ruzh commented on Logger/Logger.cpp
> +		WinRegManager reg(Hkeys::HkeyCurrentUser, regPath, AccessRights::AccessAll);
enum был убран,заменен на другое решение

2022-04-30 07:44 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			nullptr,
Добавлены поясняющие комментарии

2022-04-30 07:45 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			return nullptr;
Исправлено,изменена логика возвращения значения  из функции

2022-04-30 07:46 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +	//except
Исправлено

2022-04-30 07:46 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			0,
Добавлены поясняющие комментарии

2022-04-30 07:46 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			err = ERROR_INVALID_HANDLE;
Добавлен enum class с кодами ошибок

2022-04-30 07:47 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +	std::wstring GetSz(const std::wstring& subKey, const std::wstring& valueName, LSTATUS& err)
Исправлено

2022-04-30 07:47 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			err = ERROR_INVALID_HANDLE;
Добавлен enum class с кодами ошибок

2022-04-30 07:47 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			nullptr,
Добавлены поясняющие комментарии

2022-04-30 07:48 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +	//Reg_DWORD
Исправлено

2022-04-30 07:48 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +		//noexcept
Исправлено

2022-04-30 07:48 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +	HKEY mKey{ nullptr };
Исправлено

2022-04-30 07:49 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			nullptr);
Добавлены поясняющие комментарии

2022-04-30 07:49 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			nullptr,
Добавлены поясняющие комментарии

2022-04-30 07:49 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			nullptr,
Добавлены поясняющие комментарии

2022-04-30 07:49 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			0,
Добавлены поясняющие комментарии

2022-04-30 07:49 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			0,
Добавлены поясняющие комментарии

2022-04-30 07:51 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			throw RegException{ status,"Fail open registry key" };
Программа переведена на коды ошибок,за исключением конструктор класса Reg::Key,в котором используется исключение для предотвращения создания ключа с неопределенным состоянием

2022-04-30 07:52 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +		isOpen = true;
Неакутально,поле isOpen было убрано за ненадобностью,в связи с переработкой структуры класса

2022-04-30 07:53 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +				mKey = nullptr;
Блок удален,в связи с переработкой логики

2022-04-30 07:53 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +		isOpen = true;
Неакутально,поле isOpen было убрано за ненадобностью,в связи с переработкой структуры класса

2022-04-30 08:03 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +	void OpenKey(const Hkeys& key, const std::wstring& subkey, const AccessRights& access, LSTATUS& err)
subkey может не указывать,в случае,если необходимо открыть один из корневых ключей

2022-04-30 08:04 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +	return 0;
Функция была удалена

2022-04-30 08:05 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +inline HKEY HkeysConverter(const Hkeys& key)
Функция была удалена
Inline функции были убраны в следствие разделения решения на .h и .cpp файлы

2022-04-30 08:05 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +inline REGSAM AccessRightsConverter(const AccessRights& acc)
Функция была удалена
Inline функции были убраны в следствие разделения решения на .h и .cpp файлы

2022-04-30 08:23 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +		OpenKey(key, subKey, access);
Добавлены комментарии

2022-04-30 08:24 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +	void OpenKey(const Hkeys& key, const std::wstring& subkey, const AccessRights& access, LSTATUS& err)
Добавлены комментарии

2022-04-30 09:10 UTC, vadim-ruzh commented on Logger/Logger.cpp
> +		//registry path
Попытался убрать подобные комментарии

2022-04-30 09:12 UTC, vadim-ruzh commented on Logger/Registry.cpp
> +			reinterpret_cast<LPCBYTE>(&value),
Во всей документации,которую я находил,в данном случае использовались либо C-style касты,либо подобные касты

2022-05-09 05:08 UTC, reficul0 approved these changes

2022-05-09 05:10 UTC, reficul0 commented
Будем считать, что все замечания учтены :)

2022-05-09 05:11 UTC, merged